import streamlit as st

# Import our backend logic from the new file!
from ai_agent import generate_interview_report

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="AI Interview Master", page_icon="🧠", layout="wide")

# --- HEADER SECTION ---
st.title("🧠 AI-Powered Interview Prep & Resume Builder")
st.markdown("""
Welcome to the AI Interview Master! Upload your resume, tell us a bit about yourself, 
and paste the Job Description. Our AI agent will analyze the match, generate practice questions, 
and create a study roadmap tailored to you.
""")

st.divider()

# --- INPUT LAYOUT ---
col1, col2 = st.columns(2)

with col1:
    st.subheader("Job Details")
    job_description = st.text_area("Paste the Target Job Description", height=300, 
                                   placeholder="e.g., We are looking for a Software Engineer with experience in Python...")

with col2:
    st.subheader("Candidate Details")
    self_description = st.text_area("Self Description (Optional)", height=100, 
                                    placeholder="e.g., I am a fresh B.Tech grad passionate about AI and backend systems.")
    uploaded_resume = st.file_uploader("Upload your current Resume (PDF)", type=["pdf"])

st.divider()

# --- GENERATE BUTTON ---
generate_btn = st.button("Generate Interview Strategy", type="primary")

if generate_btn:
    if uploaded_resume and job_description:
        with st.spinner("AI is analyzing your profile against the job description. This might take a few seconds..."):
            try:
                # -----------------------------------------------------------
                # CALLING THE BRAIN: Pass the inputs to our ai_agent.py file
                # -----------------------------------------------------------
                final_report = generate_interview_report(
                    resume_file=uploaded_resume, 
                    job_desc=job_description, 
                    self_desc=self_description
                )
                
                st.success("Analysis Complete!")
                
                # Display the Markdown report generated by Gemini
                st.markdown(final_report)
                
            except Exception as e:
                st.error(f"Oops! Something went wrong: {e}")
                
    else:
        st.warning("Please upload a resume and provide a job description to proceed.")
        